{{- with .Values }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ required "Prefix of certificate and cluster issuer is required." .name }}-certificate
spec:
  {{- if .commonName }}
  commonName: {{ .commonName | quote }}
  {{- end }}
  isCA: {{ .isCA }}
  issuerRef:
    kind: "ClusterIssuer"
    name: {{ required "Prefix of certificate and cluster issuer is required." .name }}-route53-clusterissuer
  secretName: {{ required "Prefix of certificate and cluster issuer is required." .name }}-certificate-secret
  {{- if .dnsNames }}
  dnsNames: 
  {{ .dnsNames | toYaml | indent 4 }}
  {{- end }}
{{- end -}}
